"""Frozen initial synthetic Fast Arm schema. Revision 0001."""
from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapies',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('clinician_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('contraindication_rules',
    sa.Column('therapy_id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['therapy_id'], ['therapies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contraindication_rules_therapy_id'), 'contraindication_rules', ['therapy_id'], unique=False)
    op.create_table('genomic_rules',
    sa.Column('therapy_id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['therapy_id'], ['therapies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genomic_rules_therapy_id'), 'genomic_rules', ['therapy_id'], unique=False)
    op.create_table('interaction_rules',
    sa.Column('therapy_id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['therapy_id'], ['therapies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_rules_therapy_id'), 'interaction_rules', ['therapy_id'], unique=False)
    op.create_table('patient_cases',
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('therapy_evidence',
    sa.Column('therapy_id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['therapy_id'], ['therapies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapy_evidence_therapy_id'), 'therapy_evidence', ['therapy_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('library_snapshot', sa.JSON(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('configuration_hash', sa.String(length=64), nullable=False),
    sa.Column('analysis_engine_version', sa.String(length=60), nullable=False),
    sa.Column('ruleset_version', sa.String(length=80), nullable=False),
    sa.Column('therapy_library_version', sa.String(length=80), nullable=False),
    sa.Column('explanation_provider', sa.String(length=80), nullable=False),
    sa.Column('explanation_model', sa.String(length=200), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['patient_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_case_id'), 'analysis_runs', ['case_id'], unique=False)
    op.create_table('clinical_observations',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['patient_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_observations_case_id'), 'clinical_observations', ['case_id'], unique=False)
    op.create_table('genomic_observations',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['patient_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genomic_observations_case_id'), 'genomic_observations', ['case_id'], unique=False)
    op.create_table('lab_observations',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['patient_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_observations_case_id'), 'lab_observations', ['case_id'], unique=False)
    op.create_table('medication_records',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['patient_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_records_case_id'), 'medication_records', ['case_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('analysis_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_analysis_id'), 'audit_events', ['analysis_id'], unique=False)
    op.create_table('candidate_results',
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_results_analysis_id'), 'candidate_results', ['analysis_id'], unique=False)
    op.create_table('clinician_reviews',
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('clinician_id', sa.String(length=36), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('analysis_version', sa.String(length=80), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinician_reviews_analysis_id'), 'clinician_reviews', ['analysis_id'], unique=False)
    op.create_table('evidence_references',
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_references_analysis_id'), 'evidence_references', ['analysis_id'], unique=False)
    op.create_table('safety_flags',
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_flags_analysis_id'), 'safety_flags', ['analysis_id'], unique=False)
    op.create_table('uncertainty_results',
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uncertainty_results_analysis_id'), 'uncertainty_results', ['analysis_id'], unique=False)
    op.create_table('clinician_decisions',
    sa.Column('review_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=40), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['clinician_reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id')
    )
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clinician_decisions')
    op.drop_index(op.f('ix_uncertainty_results_analysis_id'), table_name='uncertainty_results')
    op.drop_table('uncertainty_results')
    op.drop_index(op.f('ix_safety_flags_analysis_id'), table_name='safety_flags')
    op.drop_table('safety_flags')
    op.drop_index(op.f('ix_evidence_references_analysis_id'), table_name='evidence_references')
    op.drop_table('evidence_references')
    op.drop_index(op.f('ix_clinician_reviews_analysis_id'), table_name='clinician_reviews')
    op.drop_table('clinician_reviews')
    op.drop_index(op.f('ix_candidate_results_analysis_id'), table_name='candidate_results')
    op.drop_table('candidate_results')
    op.drop_index(op.f('ix_audit_events_analysis_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_medication_records_case_id'), table_name='medication_records')
    op.drop_table('medication_records')
    op.drop_index(op.f('ix_lab_observations_case_id'), table_name='lab_observations')
    op.drop_table('lab_observations')
    op.drop_index(op.f('ix_genomic_observations_case_id'), table_name='genomic_observations')
    op.drop_table('genomic_observations')
    op.drop_index(op.f('ix_clinical_observations_case_id'), table_name='clinical_observations')
    op.drop_table('clinical_observations')
    op.drop_index(op.f('ix_analysis_runs_case_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_therapy_evidence_therapy_id'), table_name='therapy_evidence')
    op.drop_table('therapy_evidence')
    op.drop_table('patient_cases')
    op.drop_index(op.f('ix_interaction_rules_therapy_id'), table_name='interaction_rules')
    op.drop_table('interaction_rules')
    op.drop_index(op.f('ix_genomic_rules_therapy_id'), table_name='genomic_rules')
    op.drop_table('genomic_rules')
    op.drop_index(op.f('ix_contraindication_rules_therapy_id'), table_name='contraindication_rules')
    op.drop_table('contraindication_rules')
    op.drop_table('clinician_profiles')
    op.drop_table('auth_sessions')
    op.drop_table('users')
    op.drop_table('therapies')
    # ### end Alembic commands ###
